var rooms = [
    { "Room_No": "F-201", "Location": "EC 2nd Floor" },
    { "Room_No": "F-202", "Location": "EC 2nd Floor" },
    { "Room_No": "F-203", "Location": "EC 2nd Floor" },
    { "Room_No": "F-204", "Location": "EC 2nd Floor" },
    { "Room_No": "G-201", "Location": "IC 2nd Floor" },
    { "Room_No": "G-202", "Location": "IC 2nd Floor" },
    { "Room_No": "G-203", "Location": "IC 2nd Floor" },
    { "Room_No": "G-204", "Location": "IC 2nd Floor" },
    { "Room_No": "J-201", "Location": "CH 2nd Floor" },
    { "Room_No": "J-202", "Location": "CH 2nd Floor" },
    { "Room_No": "J-203", "Location": "CH 2nd Floor" },
    { "Room_No": "J-204", "Location": "CH 2nd Floor" },
    { "Room_No": "K-201", "Location": "IT 2nd Floor" },
    { "Room_No": "K-202", "Location": "IT 2nd Floor" },
    { "Room_No": "K-203", "Location": "IT 2nd Floor" },
    { "Room_No": "K-204", "Location": "IT 2nd Floor" },
    { "Room_No": "L-201", "Location": "2nd Floor" },
    { "Room_No": "L-202", "Location": "2nd Floor" },
    { "Room_No": "C-201", "Location": "CO 2nd Floor" },
    { "Room_No": "C-202", "Location": "CO 2nd Floor" },
    { "Room_No": "C-203", "Location": "CO 2nd Floor" },
    { "Room_No": "C-204", "Location": "CO 2nd Floor" },
    { "Room_No": "E-201", "Location": "EL 2nd Floor" },
    { "Room_No": "E-202", "Location": "EL 2nd Floor" },
    { "Room_No": "E-203", "Location": "EL 2nd Floor" },
    { "Room_No": "E-204", "Location": "EL 2nd Floor" },
    { "Room_No": "C-301", "Location": "Civil 3rd Floor" },
    { "Room_No": "C-302", "Location": "Civil 3rd Floor" },
    { "Room_No": "C-303", "Location": "Civil 3rd Floor" },
    { "Room_No": "C-304", "Location": "Civil 3rd Floor" }
];

var block_room = [
    { "block" : "1", "Room_No" : "F-201" },
    { "block" : "2", "Room_No" : "F-202" },
    { "block" : "3", "Room_No" : "F-203" },
    { "block" : "4", "Room_No" : "F-204" },
    { "block" : "5", "Room_No" : "G-201" },
    { "block" : "6", "Room_No" : "G-202" },
    { "block" : "7", "Room_No" : "G-203" },
    { "block" : "8", "Room_No" : "G-204" },
    { "block" : "9", "Room_No" : "J-201" },
    { "block" : "10", "Room_No" : "J-202" },
    { "block" : "11", "Room_No" : "J-203" },
    { "block" : "12", "Room_No" : "J-204" },
    { "block" : "13", "Room_No" : "K-204" },
    { "block" : "14", "Room_No" : "K-204" },
    { "block" : "15", "Room_No" : "K-204" },
    { "block" : "16", "Room_No" : "K-204" },
    { "block" : "17", "Room_No" : "L-201" },
    { "block" : "18", "Room_No" : "L-202" }
]

var dates = ["19-Jan-21","20-Jan-21","21-Jan-21","22-Jan-21","25-Jan-21","27-Jan-21","28-Jan-21","29-Jan-21","30-Jan-21","01-Feb-21","02-Feb-21","03-Feb-21","04-Feb-21","05-Feb-21"]
